query GetPost($id: ID!) {
  post(id: $id) {
    id
    slug
    mappingFields {
      key
      type
      value
    }
    shortContent
    publishedAt
    locked
    title
    description
    customSeoDetail {
      description
      noIndex
      thumbnail {
        ... on Image {
          id
          url
          width
          height
          dominantColorHex
          dpi
          cropHeight
          cropWidth
          cropX
          cropY
          cropZoom
          urls {
            full
            large
            medium
            small
            thumb
          }
        }
        ... on Emoji {
          id
          text
        }
        ... on Glyph {
          id
          text
          variant
        }
        ... on File {
          id
          name
          url
        }
      }
      thumbnailId
      title
      canonicalUrl
    }
    attachments {
      extension
      id
      name
      size
      url
      downloadUrl
    }
    authMemberProps {
      subscribed
      canReact
    }
    owner {
      member {
        displayName
        name
        id
        username
        profilePicture {
          ... on Image {
            id
            url
            urls {
              full
              large
              medium
              small
              thumb
            }
          }
          ... on Emoji {
            id
            text
          }
          ... on Glyph {
            id
            text
            variant
          }
          ... on File {
            id
            name
            url
          }
        }
      }
    }
    reactions {
      count
      reacted
      reaction
    }
  }
}
