query GetNetwork {
  network {
    name
    description
    images {
      lightLogo {
        ... on Image {
          id
          url
        }
        ... on Emoji {
          id
          text
        }
        ... on Glyph {
          id
          text
          variant
        }
        ... on File {
          id
          name
          url
        }
      }
      darkLogo {
        ... on Image {
          id
          url
        }
        ... on Emoji {
          id
          text
        }
        ... on Glyph {
          id
          text
          variant
        }
        ... on File {
          id
          name
          url
        }
      }
    }
  }
}
