mutation Loginuser($email: String!, $password: String!) {
  loginNetwork(input: { usernameOrEmail: $email, password: $password }) {
    accessToken
    role {
      name
      scopes
    }
    member {
      id
      name
      displayName
      username
      email
      profilePicture {
        ... on Image {
          id
          url
          width
          height
          dominantColorHex
          dpi
          cropHeight
          cropWidth
          cropX
          cropY
          cropZoom
          urls {
            full
            large
            medium
            small
            thumb
          }
        }
        ... on Emoji {
          id
          text
        }
        ... on Glyph {
          id
          text
          variant
        }
        ... on File {
          id
          name
          url
        }
      }
    }
  }
}
