query LoginCheck {
  authMember {
    id
    name
    displayName
    username
    email
    profilePicture {
      ... on Image {
        id
        url
        urls {
          full
          large
          medium
          small
          thumb
        }
      }
      ... on Emoji {
        id
        text
      }
      ... on Glyph {
        id
        text
        variant
      }
      ... on File {
        id
        name
        url
      }
    }
  }
}
