query LoginGuest($networkDomain: String!) {
  tokens(networkDomain: $networkDomain) {
    accessToken
    refreshToken
    role {
      name
      scopes
    }
    member {
      id
      name
    }
  }
}
