query replies(
  $after: String
  $before: String
  $excludePins: Boolean
  $limit: Int!
  $offset: Int
  $orderBy: PostListOrderByEnum
  $postId: ID!
  $reverse: Boolean
) {
  replies(
    after: $after
    before: $before
    excludePins: $excludePins
    limit: $limit
    offset: $offset
    orderBy: $orderBy
    postId: $postId
    reverse: $reverse
  ) {
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
    nodes {
      id
      slug
      mappingFields {
        key
        type
        value
      }
      hasMoreContent
      shortContent
      publishedAt
      owner {
        member {
          displayName
          name
          id
          username
          profilePicture {
            ... on Image {
              url
              urls {
                full
                large
                medium
                small
                thumb
              }
            }
            ... on Emoji {
              id
              text
            }
            ... on Glyph {
              id
              text
              variant
            }
            ... on File {
              id
              name
              url
            }
          }
        }
      }
    }
  }
}
