query PostReactionParticipants(
  $after: String
  $before: String
  $limit: Int!
  $offset: Int
  $postId: ID!
  $reaction: ID!
  $reverse: Boolean
) {
  postReactionParticipants(
    after: $after
    before: $before
    limit: $limit
    offset: $offset
    postId: $postId
    reaction: $reaction
    reverse: $reverse
  ) {
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      cursor
      node {
        participant {
          displayName
          name
          id
          locale
          profilePictureId
          bannerId
          status
          username
          email
          emailStatus
          newEmail
          tagline
          lastSeenAt
          createdAt
          updatedAt
          relativeUrl
          url
          externalId
          roleId
          flagged
          teammate
          staffReasons
          banner {
            ... on Image {
              __typename
              id
              url
              width
              height
              dominantColorHex
              dpi
              cropHeight
              cropWidth
              cropX
              cropY
              cropZoom
              urls {
                __typename
                full
                large
                medium
                small
                thumb
              }
            }
            ... on Emoji {
              __typename
              id
              text
            }
            ... on Glyph {
              __typename
              id
              text
              variant
            }
            ... on File {
              id
              name
              url
            }
          }
          profilePicture {
            ... on Image {
              __typename
              id
              url
              width
              height
              dominantColorHex
              dpi
              cropHeight
              cropWidth
              cropX
              cropY
              cropZoom
              urls {
                __typename
                full
                large
                medium
                small
                thumb
              }
            }
            ... on Emoji {
              __typename
              id
              text
            }
            ... on Glyph {
              __typename
              id
              text
              variant
            }
            ... on File {
              id
              name
              url
            }
          }
          authMemberProps {
            context
            scopes
            canSendPrivateMessages
            subscribed
          }
          badges {
            backgroundColor
            badgeId
            imageId
            longDescription
            text
            shortDescription
            textColor
            type
          }
          fields {
            key
            value
          }
          sessions {
            active
            country
            createdAt
            deviceBrand
            id
            ip
            lastActivityAt
            os
            osVersion
          }
          activeSession {
            active
            country
            createdAt
            deviceBrand
            id
            ip
            lastActivityAt
            os
            osVersion
          }
          score
          settings {
            privateMessaging {
              privateMessagingEnabled
            }
          }
          blockedMemberIds
          blockedMembers {
            displayName
            name
            id
            locale
            profilePictureId
            bannerId
            status
            username
            email
            emailStatus
            newEmail
            tagline
            lastSeenAt
            createdAt
            updatedAt
            relativeUrl
            url
            externalId
            roleId
            flagged
            teammate
            staffReasons
          }
        }
      }
    }
    nodes {
      participant {
        displayName
        name
        id
        locale
        profilePictureId
        bannerId
        status
        username
        email
        emailStatus
        newEmail
        tagline
        lastSeenAt
        createdAt
        updatedAt
        relativeUrl
        url
        externalId
        roleId
        flagged
        teammate
        staffReasons
        banner {
          ... on Image {
            __typename
            id
            url
            width
            height
            dominantColorHex
            dpi
            cropHeight
            cropWidth
            cropX
            cropY
            cropZoom
            urls {
              __typename
              full
              large
              medium
              small
              thumb
            }
          }
          ... on Emoji {
            __typename
            id
            text
          }
          ... on Glyph {
            __typename
            id
            text
            variant
          }
          ... on File {
            id
            name
            url
          }
        }
        profilePicture {
          ... on Image {
            __typename
            id
            url
            width
            height
            dominantColorHex
            dpi
            cropHeight
            cropWidth
            cropX
            cropY
            cropZoom
            urls {
              __typename
              full
              large
              medium
              small
              thumb
            }
          }
          ... on Emoji {
            __typename
            id
            text
          }
          ... on Glyph {
            __typename
            id
            text
            variant
          }
          ... on File {
            id
            name
            url
          }
        }
        authMemberProps {
          context
          scopes
          canSendPrivateMessages
          subscribed
        }
        badges {
          backgroundColor
          badgeId
          imageId
          longDescription
          text
          shortDescription
          textColor
          type
        }
        fields {
          key
          value
        }
        sessions {
          active
          country
          createdAt
          deviceBrand
          id
          ip
          lastActivityAt
          os
          osVersion
        }
        activeSession {
          active
          country
          createdAt
          deviceBrand
          id
          ip
          lastActivityAt
          os
          osVersion
        }
        score
        settings {
          privateMessaging {
            privateMessagingEnabled
          }
        }
        blockedMemberIds
        blockedMembers {
          displayName
          name
          id
          locale
          profilePictureId
          bannerId
          status
          username
          email
          emailStatus
          newEmail
          tagline
          lastSeenAt
          createdAt
          updatedAt
          relativeUrl
          url
          externalId
          roleId
          flagged
          teammate
          staffReasons
        }
      }
    }
  }
}
